# Generated by Django 4.1.2 on 2022-11-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=20)),
                ('anotacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='proceso',
            name='juzgado',
            field=models.CharField(max_length=30),
        ),
    ]
